=== helsingborg-stad/app-helsingborg-guide/guide-app/json-schemas/IGuide.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "ContentType": {
      "enum": ["audio", "video"],
      "type": "string"
    },
    "GuideType": {
      "enum": ["guide", "trail"],
      "type": "string"
    },
    "IBeacon": {
      "properties": {
        "distance": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "nid": {
          "type": "string"
        }
      },
      "required": ["id", "nid"],
      "type": "object"
    },
    "IContentObject": {
      "properties": {
        "audio": {
          "$ref": "#/definitions/IMediaContent"
        },
        "beacon": {
          "$ref": "#/definitions/IBeacon"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "images": {
          "items": {
            "$ref": "#/definitions/IImageUrls"
          },
          "type": "array"
        },
        "links": {
          "items": {
            "$ref": "#/definitions/ILink"
          },
          "type": "array"
        },
        "location": {
          "$ref": "#/definitions/ILocation"
        },
        "order": {
          "type": "number"
        },
        "postStatus": {
          "$ref": "#/definitions/PostStatus"
        },
        "searchableId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "video": {
          "$ref": "#/definitions/IMediaContent"
        }
      },
      "required": [
        "id",
        "images",
        "order",
        "postStatus",
        "searchableId",
        "title"
      ],
      "type": "object"
    },
    "IImageUrls": {
      "properties": {
        "large": {
          "type": ["null", "string"]
        },
        "medium": {
          "type": ["null", "string"]
        },
        "thumbnail": {
          "type": ["null", "string"]
        }
      },
      "type": "object"
    },
    "ILink": {
      "properties": {
        "title": {
          "type": "string"
        },
        "type": {
          "enum": [
            "facebook",
            "instagram",
            "spotify",
            "twitter",
            "vimeo",
            "web",
            "youtube"
          ],
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["url"],
      "type": "object"
    },
    "ILocation": {
      "properties": {
        "id": {
          "type": "number"
        },
        "latitude": {
          "type": "number"
        },
        "links": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/ILink"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "longitude": {
          "type": "number"
        },
        "openingHourExceptions": {
          "items": {
            "$ref": "#/definitions/IOpeningHourException"
          },
          "type": "array"
        },
        "openingHours": {
          "items": {
            "$ref": "#/definitions/IOpeningHours"
          },
          "type": "array"
        },
        "streetAddress": {
          "type": ["null", "string"]
        }
      },
      "required": ["id", "latitude", "links", "longitude", "streetAddress"],
      "type": "object"
    },
    "IMediaContent": {
      "properties": {
        "contentType": {
          "$ref": "#/definitions/ContentType"
        },
        "created": {
          "format": "date-time",
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "modified": {
          "format": "date-time",
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "contentType",
        "created",
        "description",
        "id",
        "modified",
        "title",
        "url"
      ],
      "type": "object"
    },
    "IOpeningHourException": {
      "properties": {
        "date": {
          "format": "date-time",
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": ["date", "description"],
      "type": "object"
    },
    "IOpeningHours": {
      "properties": {
        "closed": {
          "type": "boolean"
        },
        "closing": {
          "type": ["null", "string"]
        },
        "dayNumber": {
          "enum": [1, 2, 3, 4, 5, 6, 7],
          "type": "number"
        },
        "opening": {
          "type": ["null", "string"]
        },
        "weekday": {
          "type": "string"
        }
      },
      "required": ["closed", "dayNumber", "opening", "weekday"],
      "type": "object"
    },
    "PostStatus": {
      "enum": ["draft", "publish"],
      "type": "string"
    }
  },
  "properties": {
    "childFriendly": {
      "type": "boolean"
    },
    "contentObjects": {
      "items": {
        "$ref": "#/definitions/IContentObject"
      },
      "type": "array"
    },
    "dateEnd": {
      "format": "date-time",
      "type": "string"
    },
    "dateStart": {
      "format": "date-time",
      "type": "string"
    },
    "description": {
      "type": ["null", "string"]
    },
    "guideGroupId": {
      "type": "number"
    },
    "guideType": {
      "$ref": "#/definitions/GuideType"
    },
    "id": {
      "type": "number"
    },
    "images": {
      "$ref": "#/definitions/IImageUrls"
    },
    "location": {
      "$ref": "#/definitions/ILocation"
    },
    "name": {
      "type": "string"
    },
    "postStatus": {
      "$ref": "#/definitions/PostStatus"
    },
    "slug": {
      "type": "string"
    },
    "tagline": {
      "type": ["null", "string"]
    }
  },
  "required": [
    "childFriendly",
    "contentObjects",
    "guideGroupId",
    "guideType",
    "id",
    "images",
    "name",
    "postStatus",
    "slug"
  ],
  "type": "object"
}

=== helsingborg-stad/app-helsingborg-guide/guide-app/src/utils/__tests__/testData02/guide.json
{
  "childFriendly": false,
  "contentObjects": [
    {
      "id": "59b28763cd49d",
      "images": [
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-skize-2.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-skize-2-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-skize-2-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-dsc00081.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-dsc00081-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-dsc00081-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Jimmy.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Jimmy-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Jimmy-150x150.png"
        }
      ],
      "order": 0,
      "postStatus": "publish",
      "searchableId": "001",
      "title": "Jimmy Skize - Color Invasion",
      "description": "Jimmy Skize skapade det första verket i #ArtStreetHbg. Hans uppdrag var att förkroppsliga ambitionen med hela projektet i ett enda verk på Bussterminalen, Helsingborg C.\n”Color Invasion” berättar i bild om hur robotar tar över Helsingborg med hjälp av färg. Något som kan liknas vid #ArtStreetHbg:s ambition med projektet – att sätta färg på det offentliga rummet.\nJimmy Skize är en av Sveriges bästa graffittiartister och har ett öga för detaljer som få andra. Han lägger mycket tid och detaljer på att skapa lager av färg som tillsammans blir en imponerande bild.\n",
      "audio": {
        "contentType": "audio",
        "created": "2017-09-29T13:17:25.000Z",
        "description": "Berättelse om Jimmy Skizes konstverk \"Color Invasion\"",
        "id": 51883,
        "modified": "2017-09-29T13:17:42.000Z",
        "title": "Jimmy Skize",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Jimmy-Skize.mp3"
      },
      "video": {
        "contentType": "video",
        "created": "2017-09-25T07:29:19.000Z",
        "description": "Intervju med Jimmy Skize i #artstreethbg. Konstnären bakom \"Color invasion\" på knutpunktens bussterminal.",
        "id": 50939,
        "modified": "2017-09-25T07:31:27.000Z",
        "title": "Jimmy Skize",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Intervju-Jimmy-Skize_1.mp4"
      },
      "links": [
        {
          "title": "Jimmy Skize webbplats",
          "url": "http://www.skize.se/"
        },
        {
          "title": "Jimmy Skize Instagram",
          "url": "https://www.instagram.com/skize_cas/"
        }
      ],
      "beacon": {
        "distance": 15,
        "id": "346738505575",
        "nid": "f7826da6bc5b71e0893e"
      },
      "location": {
        "id": 47810,
        "latitude": 56.04353,
        "links": null,
        "longitude": 12.69381,
        "streetAddress": "Terminalgatan 3"
      }
    },
    {
      "id": "59b28763e7916",
      "images": [
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse_2.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse_2-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse_2-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-Ilse-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Ilse-1024x1024.jpg",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Ilse-300x300.jpg",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Ilse-150x150.jpg"
        }
      ],
      "order": 1,
      "postStatus": "publish",
      "searchableId": "002",
      "title": "Ilse Weisfelt - Mr. Fisherman",
      "description": "Titta upp! Mr. Fisherman kräver att du höjer blicken och tittar högt upp på taknocken på Södergatan. Verket skapades av den holländska grafikern och konstnären Ilse Weisfelt. Med hjälp av Kulturmagasinet har hon skapat en bild som knyter an till Helsingborgs stads historia som fiskeläge.\nMr. Fisherman sitter på en utmanande plats både för konstnären och besökaren. Från början trodde Ilse att väggen var av betong som hon kunde måla med vanlig färg på – men det visade sig vara grusad plywood. Så hon fick använda sig av sprayfärg istället. Inga problem för Ilse!\nIlse har varit verksam som grafiker och illustratör i flera år och har producerat material för flera kunder. Det var hennes pojkvän som fick henne intresserad av muralmålningar, något som hon nu behärskar till fullo.\n",
      "audio": {
        "contentType": "audio",
        "created": "2017-09-29T13:19:59.000Z",
        "description": "Berättelse om Iles Weisfelts konstverk Mr. Fisherman",
        "id": 51887,
        "modified": "2017-09-29T13:20:22.000Z",
        "title": "Ilse Weisfelt",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Ilse-Weisfelt.mp3"
      },
      "video": {
        "contentType": "video",
        "created": "2017-09-25T07:35:22.000Z",
        "description": "Intervju med Ilse Weisfelt i #artstreethbg. Konstnären bakom Mr. Fisherman på Södergatan.",
        "id": 50942,
        "modified": "2017-09-25T07:35:43.000Z",
        "title": "Intervju - Ilse Weisfelt",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Intervju-Ilse-Weisfelt.mp4"
      },
      "links": [
        {
          "title": "Ilse Weisfelts Instagram",
          "url": "https://www.instagram.com/ilseweisfelt/"
        },
        {
          "title": "Ilse Weisfelts webbplats",
          "url": "http://www.ilseweisfelt.com/"
        }
      ],
      "beacon": {
        "distance": 40,
        "id": "6f6b567a6a76",
        "nid": "f7826da6bc5b71e0893e"
      },
      "location": {
        "id": 47812,
        "latitude": 56.042545,
        "links": null,
        "longitude": 12.700915,
        "streetAddress": "Södergatan 10"
      }
    },
    {
      "id": "59b2876408db5",
      "images": [
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0398.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0398-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0398-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0830.png",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0830-300x300.png",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/1000x1000-_MG_0830-150x150.png"
        },
        {
          "large": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/SpiderTag-1024x1024.jpg",
          "medium": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/SpiderTag-300x300.jpg",
          "thumbnail": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/SpiderTag-150x150.jpg"
        }
      ],
      "order": 2,
      "postStatus": "publish",
      "searchableId": "003",
      "title": "SpiderTag - Untitled 26",
      "description": "Verket av SpiderTag är hans största hitintills med ljuskablar. Vi är stolta över att det är just i Helsingborg som han valt att lägga mycket energi och tid!\nSpiderTag, multikonstnär från Argentina, har provat flera olika konstformer innan han fastnade för ljuskablar. Han började egentligen med garn och blev på den vägen intresserade av hur garn och färg kan bilda nya mönster och former – för att slutligen kombinera det med ljus.\nLjuskablarna är så kallade optiska fiber! Optiska fiber är betydligt böjligare och följsammare än till exempel LED-lister. Det gör att man kan jobba med dem ungefär som garn.\n",
      "audio": {
        "contentType": "audio",
        "created": "2017-09-29T13:21:44.000Z",
        "description": "Berättelse om konstverket av SpiderTag",
        "id": 51890,
        "modified": "2017-09-29T13:21:53.000Z",
        "title": "SpiderTag",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/SpiderTag.mp3"
      },
      "video": {
        "contentType": "video",
        "created": "2017-09-25T07:36:24.000Z",
        "description": "Intervju med konstnären \"SpiderTag\". Konstnären bakom ljuskonstverket på Södergatan vid spelhallen.",
        "id": 50944,
        "modified": "2017-09-25T07:36:46.000Z",
        "title": "Intervju - SpiderTag",
        "url": "https://api.helsingborg.se/wp-content/uploads/sites/2/2017/09/Intervju-SpiderTag.mp4"
      },
      "links": [
        {
          "title": "SpiderTags Instagram",
          "url": "https://www.instagram.com/spidertag/"
        },
        {
          "title": "SpiderTags Facebook-sida",
          "url": "https://www.facebook.com/spidertag/"
        }
      ],
      "beacon": {
        "distance": 40,
        "id": "4a5a50717673",
        "nid": "f7826da6bc5b71e0893e"
      },
      "location": {
        "id": 47814,
        "latitude": 56.040165,
        "links": null,
        "longitude": 12.702522,
        "streetAddress": "Södergatan 19"
      }
    },
    {
